version: '3.4'

networks:
  k6:
  grafana:

services:
  influxdb:
    image: influxdb:1.8
    #    entrypoint: /bin/sh
    #    user: root
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 2048M

  grafana:
    image: grafana/grafana:8.5.14
    #    entrypoint: /bin/sh
    #    user: root
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  k6-api:
    build:
      context: .
      dockerfile: k6-api.dockerfile
    image: base-apm-k6-qa
    volumes:
      - ./scripts:/base-apm-k6-qa/scripts
      - ./reports/html:/base-apm-k6-qa/reports/html
    networks:
      - k6
    ports:
      - "6565:6565"
      - "8443:8443"

  k6-front:
    build:
      context: .
      dockerfile: k6-front.dockerfile
    image: base-apm-k6-qa
    volumes:
      - ./scripts:/base-apm-k6-qa/scripts
      - ./reports/html:/base-apm-k6-qa/reports/html
      - ./reports/screenshots:/base-apm-k6-qa/reports/screenshots
    networks:
      - k6
    ports:
      - "6565:6565"
      - "8443:8443"

  k6-kafka:
    build:
      context: .
      dockerfile: k6-kafka.dockerfile
    image: base-apm-k6-qa
    volumes:
      - ./scripts:/base-apm-k6-qa/scripts
      - ./reports/html:/base-apm-k6-qa/reports/html
    networks:
      - k6
    ports:
      - "6565:6565"
      - "8443:8443"

  k6-socket:
    build:
      context: .
      dockerfile: k6-socket.dockerfile
    image: base-apm-k6-qa
    volumes:
      - ./scripts:/base-apm-k6-qa/scripts
      - ./reports/html:/base-apm-k6-qa/reports/html
    networks:
      - k6
    ports:
      - "6565:6565"
      - "8443:8443"

  k6-sqs:
    build:
      context: .
      dockerfile: k6-sqs.dockerfile
    image: base-apm-k6-qa
    volumes:
      - ./scripts:/base-apm-k6-qa/scripts
      - ./reports/html:/base-apm-k6-qa/reports/html
    networks:
      - k6
    ports:
      - "6565:6565"
      - "8443:8443"